import { next, rewrite } from '@vercel/functions';

// AI/answer-engine crawlers that fetch a page live and generally do NOT
// execute JavaScript (confirmed for GPTBot via 500M+ real request analysis:
// see the sources noted in the project's GEO/AEO backlog doc, item 11).
// This SPA renders everything client-side, so without this middleware these
// crawlers fetch an almost-empty HTML shell instead of the real content.
// Google/Bing are included too since their own render pipeline reads the
// same static snapshot fine and it is strictly cheaper for them to fetch.
const BOT_USER_AGENT = new RegExp(
  [
    'GPTBot',
    'ChatGPT-User',
    'OAI-SearchBot',
    'ClaudeBot',
    'Claude-Web',
    'Claude-SearchBot',
    'Claude-User',
    'PerplexityBot',
    'Perplexity-User',
    'Google-Extended',
    'Googlebot',
    'Bingbot',
    'CCBot',
    'anthropic-ai',
    'cohere-ai',
    'Bytespider',
    'facebookexternalhit',
    'Applebot',
  ].join('|'),
  'i'
);

// Route -> its build-time prerendered HTML snapshot (public/prerendered/*.html,
// regenerated by `node prerender.mjs`). Only static, Firestore-independent
// routes are covered here; the Firestore-backed /blog and /blog/:slug pages
// are a separate, still-open piece of work (backlog item 11).
const STATIC_SNAPSHOTS: Record<string, string> = {
  '/': '/prerendered/home.html',
  '/profitscout': '/prerendered/profitscout.html',
  '/soft-clipper': '/prerendered/soft-clipper.html',
  '/privacy': '/prerendered/privacy.html',
  '/terms': '/prerendered/terms.html',
  '/profitscout-privacy': '/prerendered/profitscout-privacy.html',
};

export const config = {
  matcher: [
    '/',
    '/profitscout',
    '/soft-clipper',
    '/privacy',
    '/terms',
    '/profitscout-privacy',
  ],
};

export default function middleware(request: Request) {
  const userAgent = request.headers.get('user-agent') || '';
  const url = new URL(request.url);
  const snapshotPath = STATIC_SNAPSHOTS[url.pathname];

  if (snapshotPath && BOT_USER_AGENT.test(userAgent)) {
    return rewrite(new URL(snapshotPath, request.url));
  }

  // Everyone else (real visitors, and any bot on an uncovered route) gets
  // the normal SPA, unchanged.
  return next();
}
